### ISSUE TITLE
(copy of) A blockchain in 200 lines of code?

### ISSUE THREAD

**Issue by sks7g** [SavjeeTutorials/SavjeeCoin#2]
Hello, please don't misunderstand me, I think it is good to extend and pass on your knowledge, but

Where is the **big** difference to the code of Lauri Hartikka?
See her: https://github.com/lhartikk/naivechain
Why a new name (!)

But you didn't reinvent this wheel, why don't you fork it? 
Sorry, for this comment.....

**Comment by Savjee** [comment]
I understand your point of view, but want to clarify why this repository exists:

First of all: I wasn't aware of that project. Must Google better!

Secondly: I created this code to demonstrate how a blockchain works on a very basic level. It was made just for my YouTube video. It's just a proof-of-concept and misses a lot of features of a real blockchain. It's not my intend to make a real project out of this.

And thirdly: You could say that the other project also "reinvents the wheel" because blockchains already exist.

I'll close this comment for now because this is not a real issue. You can however continue making comments here.

**Comment by sks7g** [comment]
Xavier, thank you for your quick reply and your frank words, that was great! Also your videos and your channel is great, no question. 

As I said, I saw the code "naivechain" and then "yours", both in Javascript, so identical (---> software pattern)... Hashtables, binary, merkle trees and some other software patterns are older than the two of us together :)

I wishing you and your family a joyous and peaceful Christmas. 
May you be blessed with lots of love from the ones that matter most.
