### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by subversivo58** [SavjeeTutorials/SavjeeCoin#9]
Hi @Savjee, I've been following your series of posts and I really enjoyed that.

I do not like the idea of ​​"reinventing the wheel", but if you intend to create some decentralized solution that uses a blockchain template, you can do thousands of searches (from various sources) (Googling) that only topics related to "cryptocurrency" flood the content.

Virtually most solutions, services and tools have open sources that can be studied and documentation plentiful but, you end up stuck or one or the other ... it is extremely scarce to find blockchain materials that are not solely and exclusively related to "cryptocurrency ". I really do not believe that I should "mold" my problems in order to use the available libraries simply because of the lack of a minimally qualified material.

I think at this point that your series of posts has been very didactic and helps better understand the operation of a blockchain than many low-level matters that it has there.

I'm studying the use of a front-end blockchain using WebRTC (DataChannel), and I'm leveraging their stuff to better understand how it works. In the last post it seems to me that you have gone in the direction of an active chain (cryptocurrency).

I wonder if you have thoughts about continuing the series of posts and plans to talk about wallets or contracts?

**Comment by Savjee** [comment]
I'm closing this issue because it's not really a problem with the code. But feel free to keep commenting afterwards ;) 

I do plan to continue the series but I don't know yet what the next video will be and when I'll get around to making it. I think almost everything is in place to support wallets. All it needs is a way for people to sign transactions (HMAC) and a way for miners to validate them (also HMAC). After that, the wallet can be implemented as a front-end for this blockchain.

Contracts is a bit more difficult to implement in node.js (in a safe way) but not impossible. I've been thinking about wether or not the safety measurements would be too complicated for this series.
